name: AWS Login
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Access Key'
        required: true
    outputs:
      token:
        description: Old Version
        value: ${{ jobs.AWS-Login.outputs.token }}
jobs:
  AWS-Login:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.value }}
    steps:
      - uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Get token
        id: get-token
        run: |
          token=$(aws ecr get-login-password --region eu-central-1)
          echo "value=$token" >> "$GITHUB_OUTPUT"
