name: Validate AWS Credentials with Token

on:
  workflow_dispatch:

jobs:
  validate-credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Verify AWS CLI installation
        run: |
          if ! command -v aws &> /dev/null; then
            echo "AWS CLI is not installed."
            exit 1
          else
            echo "AWS CLI is installed."
          fi

      - name: Set environment variables
        run: |
          echo "Setting environment to TEST and region to eu-central-1"
          echo "ENV=TEST" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - name: Configure AWS credentials and get token
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify AWS secrets are set
        run: |
          if [[ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" || -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then
            echo "AWS secrets are missing or empty."
            exit 1
          else
            echo "AWS secrets are set."
          fi

      - name: Get ECR login token
        id: get-token
        run: |
          token=$(aws ecr get-login-password --region eu-central-1)
          echo "value=$token" >> "$GITHUB_OUTPUT"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Validate AWS credentials with token
        run: |
          echo "Testing AWS credentials and token by listing S3 buckets..."
          aws sts get-caller-identity || echo "AWS credentials validation failed."
          aws s3 ls || echo "AWS credentials validation failed."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ steps.get-token.outputs.value }}
