name: S3 List

on:
  workflow_dispatch:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

env:
  AWS_REGION: eu-central-1

jobs:
  AWS-Login:
    uses: doruardelean/python-aws/.github/workflows/aws-login.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  Setup:
    needs: [ AWS-Login ]
    runs-on: ubuntu-latest
    steps:
      - name: List S3 buckets
        id: s3-list
        env:
          AWS_PROFILE: default  # Set AWS_PROFILE to use the default profile
        run: |
          echo "Testing AWS credentials by listing S3 buckets..."
          bucket_list=$(aws s3 ls)
          if [ -z "$bucket_list" ]; then
            echo "No S3 buckets found or credentials validation failed."
          else
            echo "S3 buckets:"
            echo "$bucket_list"
          fi
