name: S3 List

on:
  workflow_dispatch:
env:
  AWS_REGION: eu-central-1

jobs:
  Setup:
    runs-on: ubuntu-latest
    environment: TEST  # Specify the environment to access environment secrets
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access the environment secret
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Access the environment secret
          aws-region: eu-central-1

      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity || echo "AWS credentials validation failed."
      
      - name: List S3 buckets
        run: |
          echo "Testing AWS credentials by listing S3 buckets..."
          bucket_list=$(aws s3 ls)
          if [ -z "$bucket_list" ]; then
            echo "No S3 buckets found or credentials validation failed."
          else
            echo "S3 buckets:"
            echo "$bucket_list"
          fi
